#ifndef HARD_SPHERE
#define HARD_SPHERE

#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <random>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <Eigen/Dense>

namespace hsmc {

using Coord3D = Eigen::Matrix<double, 3, Eigen::Dynamic, Eigen::RowMajor>;
using CellIndices =
    Eigen::Matrix<int, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;
using Vec3D = Eigen::Vector3d;
using Vec2D = Eigen::Vector2d;

/*
 * Calculate the N-Dimensional Cartesian product
 *
 * Example:
 *      product_nd([[1, 2], [3, 4]]) -> [[1, 3], [1, 4], [2, 3], [2, 4]]
 */
template<class T>
std::vector<std::vector<T>> product_nd(const std::vector<std::vector<T>>& arrays);

/*
* Bheaving like ``numpy.unravel_index`` with 'C' order (last axis changing fastest)
*/
std::vector<int> unravel_index(int index, const std::vector<int>& shape);

/*
 * Applying periodic boundary conditions in any dimension, the pbc
 *      in each dimension can be turned off
 * The dimension is inferred from class T, which is an Eigen matrix
 *      with shape (dimension, n_particles)
 */
template<class T>
class PBC {
  public:
    PBC(std::vector<double> box, std::vector<bool> is_pbc)
        : box_{std::move(box)},
          dim_{static_cast<int>(box_.size())},
          is_pbc_{std::move(is_pbc)} {
        if (box_.size() != is_pbc_.size()) {
            throw std::runtime_error("PBC box size mismatch");
        }
        refresh_cache();
        update_volume();
    }

    std::vector<double> box_;

    void fix_position(T& positions) const;
    void fix_position(T& positions, int i) const;
    double get_dist_sq(const T& positions, int i, int j) const;

    void rescale(double scale) {
        for (double& side : box_) {
            side *= scale;
        }
        refresh_cache();
        update_volume();
    }

    void rescale(double scale, int axis) {
        if (axis < dim_) {
            box_[axis] *= scale;
            refresh_cache();
            update_volume();
            return;
        }
        throw std::runtime_error("Trying to rescale with invalid axis index");
    }

    double volume_ = 0.0;

  private:
    int dim_ = 0;
    std::vector<bool> is_pbc_;
    std::array<double, 3> box_cache_{{1.0, 1.0, 1.0}};
    std::array<double, 3> inv_box_cache_{{1.0, 1.0, 1.0}};
    std::array<bool, 3> is_pbc_cache_{{false, false, false}};

    void update_volume();
    void refresh_cache();
    double axis_box(int axis) const;
    double axis_inv_box(int axis) const;
    bool axis_is_pbc(int axis) const;
};

/*
 * Using the Verlet list to accelerate distance calculation with a
 *     cutoff for simulation in all dimensions
 * The dimension is inferred from class T, which is an Eigen matrix
 *      with shape (dimension, n_particles)
 */
template<class T>
class VerletList {
  public:
    VerletList(double r_cut, double r_skin);

    void build(const T& positions);
    void build(const T& positions, const PBC<T>& boundary);
    std::vector<int> get_neighbours(int i) const;

    int begin_offset(int i) const { return point_[i]; }
    int end_offset(int i) const { return point_[i + 1]; }
    int neighbour_at(int offset) const { return nlist_[offset]; }

    double dr_sq_;

  private:
    std::vector<int> nlist_;
    std::vector<int> point_;
    double rc_;
    double rc2_;
    double rl_;
    double rl2_;
    int point_size_ = 0;
    int size_ = 0;
};

/*
 * Using the Cell linked list to accelerate the distance calculation
 *      for simulation in all dimensions
 * The dimension is inferred from class T, which is an Eigen matrix
 *      with shape (dimension, n_particles)
 */
template<class T>
class CellList {
  public:
    CellList(double r_cut, std::vector<double> box, std::vector<bool> is_pbc);
    void build(const T& positions);

  private:
    int dim_;
    double r_cut_;
    int sc_;
    int size_;
    std::vector<int> head_shape_;
    std::vector<double> box_;
    std::vector<bool> is_pbc_;
    PBC<T> boundary_;
};

/*
 * Dump the current phase point to an xyz file
 * It works with both 2D and 3D system
 */
template<class T>
void dump(const T& system, const std::string& filename);

/*
 * Load the phase point from the *last* frame of an xyz file, then rebuild the
 *      neighbour list.
 * It works with both 2D and 3D system, and the xyz file should be generated by
 *      the `dump` function
 */
template<class T>
void load(T& system, const std::string& filename);

/*
 * Hard Sphere Monte-Carlo simulation without neighbout lists
 */
class HSMC {
  public:
    HSMC(
        int n, std::vector<double> box,
        std::vector<bool> is_pbc, std::vector<bool> is_hard, double r_skin,
        bool scale_fixed_particles = true
    );

    int dim_ = 3;
    int n_;
    std::vector<double> box_;
    Coord3D positions_;

    void fill_ideal_gas();
    void fill_hs();
    void sweep();

    void crush(double target_vf, double delta_vf);
    void crush_along_axis(double target_vf, double delta_vf, int axis);

    double get_vf() const {
        return static_cast<double>(n_) * M_PI / (boundary_.volume_ * 6.0);
    }

    void rebuild_nlist() {
        vlist_.build(positions_, boundary_);
        total_disp_.setZero();
        ldi_ = 0;
    }

    void set_indices(const std::vector<int>& indices) {
        rand_indices_ = indices;
    }

    bool report_overlap();

    Coord3D& get_positions() { return positions_; }
    std::vector<double> get_box() { return box_; }
    const Coord3D& view_positions() const { return positions_; }
    void load_positions(Coord3D positions) {
        positions_ = std::move(positions);
        rebuild_nlist();
    }
    std::string repr() const;
    std::string str() const;

  private:
    double step_ = 1.0;
    PBC<Coord3D> boundary_;
    Coord3D total_disp_;
    std::vector<bool> is_pbc_;
    std::vector<bool> is_hard_;
    std::vector<int> hard_dim_;
    std::vector<int> rand_indices_;
    bool scale_fixed_particles_ = true;
    VerletList<Coord3D> vlist_;
    int ldi_ = 0;
    std::mt19937 rng_;
    std::uniform_real_distribution<double> unit_dist_;
    std::uniform_real_distribution<double> symmetric_dist_;

    std::vector<std::array<int, 2>> get_overlap_indices();
    std::vector<int> get_neighbours(int i) const {
        return vlist_.get_neighbours(i);
    }

    Vec3D random_position();
    Vec3D random_displacement();
    bool advance(int idx);
    void remove_overlap();
    void shuffle_indices();
    bool check_overlap(int idx);
    bool check_overlap();
    bool check_hardwall();
    bool check_hardwall(int idx);
    void check_disp_sum(int idx, const Vec3D& disp);
    void adjust_step(int accept_number);
};

#include "hard_sphere.tpp"

}  // namespace hsmc

#endif
